# Generated by Django 4.2.2 on 2023-08-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='تصویر اسلایدر')),
                ('data_slide_to', models.CharField(default=None, max_length=200, verbose_name='شماره تصویر')),
            ],
        ),
    ]
