# Generated by Django 4.2.2 on 2023-08-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepictures',
            name='data_slide_to',
        ),
    ]
