# Generated by Django 4.2.2 on 2023-08-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_remove_homepictures_data_slide_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=2000, verbose_name='جواب')),
                ('location', models.TextField(max_length=2000, verbose_name='جواب')),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
    ]
