# Generated by Django 4.2.2 on 2023-08-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_homeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='info',
            field=models.TextField(max_length=2000, verbose_name='اطلاعات هنرستان'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='location',
            field=models.TextField(max_length=2000, verbose_name='موقیعت مکانی هنرستان'),
        ),
    ]
