# Generated by Django 4.2.2 on 2023-08-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_alter_homeinfo_info_alter_homeinfo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='شماره تلفن هنرستان'),
        ),
    ]
