# Generated by Django 4.2.2 on 2023-08-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_alter_homeinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='slogan',
            field=models.CharField(default=None, max_length=200, verbose_name='شعار هنرستان'),
        ),
    ]
