# Generated by Django 4.2.2 on 2023-09-07 10:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0006_homeinfo_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='location',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='موقیعت مکانی هنرستان'),
        ),
    ]
