# Generated by Django 4.2.2 on 2023-09-07 13:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0007_alter_homeinfo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='اطلاعات هنرستان'),
        ),
    ]
