# Generated by Django 4.2.2 on 2023-08-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='lesson_sections',
            field=models.CharField(default='', max_length=500, verbose_name='درس'),
        ),
    ]
