# Generated by Django 4.2.2 on 2023-09-07 18:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_faq_lesson_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='awnser',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='جواب'),
        ),
    ]
