# Generated by Django 4.2.2 on 2023-09-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_faq_awnser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionchoice',
            options={'verbose_name': 'رشته', 'verbose_name_plural': 'رشته ها'},
        ),
    ]
