# Generated by Django 4.2.2 on 2023-09-07 17:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_works_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='caption',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات نمونه کار'),
        ),
    ]
