# Generated by Django 4.2.2 on 2023-09-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_circular_text_alter_notification_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'اطلاعیه', 'verbose_name_plural': 'اطلاعیه ها'},
        ),
    ]
