# Generated by Django 4.2.2 on 2023-09-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_ipaddress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'آی پی', 'verbose_name_plural': 'آی پی ها'},
        ),
    ]
